# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: Camkes VM

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        march: [nehalem, armv7a, armv8a]
    steps:
    - uses: axel-h/ci-actions/camkes-vm@patch-axel-7
      with:
        march: ${{ matrix.march }}
